### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by DrOreo002** [iso2013/PacketEntityAPI#1]
* Steps to reproduce
Not sure it just happens randomly

* Minecraft version *(Only 1.12 is officially supported)*
1.12.2

Log

https://pastebin.com/Vixd30ap

**Comment by DrOreo002** [comment]
Ummmm????, hello?

**Comment by iso2013** [comment]
1.12 and below require use of the legacy version, have you double checked that you are running with the legacy jar?

I should really add an L to the legacy version's version so I can tell by looking at the log....

**Comment by DrOreo002** [comment]
> 1.12 and below require use of the legacy version, have you double checked that you are running with the legacy jar?
> 
> I should really add an L to the legacy version's version so I can tell by looking at the log....

Hmmmm, I've used the version that had the Legacy tag on it, not sure why its still throwing that error

**Comment by iso2013** [comment]
Fixed as of latest commit, releasing within the week.
